version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: on-failure
    networks:
      - vax_net
  notary:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/notary
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    restart: on-failure
    read_only: true
    networks:
      - vax_net
  directory:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/directory
    environment:
      - PORT=8080
    ports:
      - 8081:8080
    restart: on-failure
    read_only: true
    networks:
      - vax_net
  manufacturer:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/manufacturer
    environment:
      - PORT=8080
      - ACTOR_ID=manu_01
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NOTARY_HOST=notary
      - NOTARY_PORT=8080
    ports:
      - 8082:8080
    restart: on-failure
    read_only: true
    networks:
      - vax_net
  authority:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/authority
    environment:
      - PORT=8080
      - ACTOR_ID=auth_01
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NOTARY_HOST=notary
      - NOTARY_PORT=8080
    ports:
      - 8083:8080
    restart: on-failure
    read_only: true
    networks:
      - vax_net
  customer:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/customer
    environment:
      - PORT=8080
      - ACTOR_ID=cust_01
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NOTARY_HOST=notary
      - NOTARY_PORT=8080
    ports:
      - 8084:8080
    restart: on-failure
    read_only: true
    networks:
      - vax_net

networks:
  vax_net:
    driver: bridge
